-- Tạo user
CREATE USER 'admin'@'%' IDENTIFIED BY 'thuylinh';
GRANT ALL PRIVILEGES ON *.* TO 'admin'@'%' WITH GRANT OPTION;
FLUSH PRIVILEGES;

CREATE USER 'admin1'@'%' IDENTIFIED BY 'haidang';
GRANT ALL PRIVILEGES ON *.* TO 'admin1'@'%' WITH GRANT OPTION;
FLUSH PRIVILEGES;

-- Tạo database
CREATE DATABASE auth_db;
CREATE DATABASE user_db;
CREATE DATABASE game_db;
